### ISSUE TITLE
Learning step

### ISSUE THREAD

**Issue by joyyang1215** [rrahmati/roboinstruct-2#4]
Hi
As you say, after collecting all the training data, I should train the vision part weights (VAE-GAN) first.
And then, copy the pre-trained model to another folder, and train the rest control part (LSTM).

What I want to ask is that: In the second step, **should I fine-tune the pre-trained vae-gan when learning the LSTM? Or should I fix the VAE-GAN weights and just learn the LSTM?**
Thanks

**Comment by rrahmati** [comment]
No, what the vision part (Chainer code) gives you is the features extracted from the encoder regularized using LSTM controller. So, the second phase of training only trains the LSTM network on the extracted features.

**Comment by joyyang1215** [comment]
Thank you so miuch
