### ISSUE TITLE
time step of LSTM

### ISSUE THREAD

**Issue by joyyang1215** [rrahmati/roboinstruct-2#5]
Hi, 
I would like to implement your control model.
In your code, there's `config['seq_length'] = 50  # number of chars in the sequence`
Does it also mean the time steps of LSTM?

**Comment by rrahmati** [comment]
Hi,

Yes, it is the number of time-steps for training LSTM. I fixed it in the code.

**Comment by joyyang1215** [comment]
So, when sampling frequency is 4Hz, every demonstration should be completed within 12.5(i.e. 50/4) sec. Am I right?
And how to determine the batch size of LSTM?
THX

**Comment by rrahmati** [comment]
Not necessarily. A command can be to send the robot to some joint angles but we do not reach there in time. This can happen in test time as long as it also happens in training time.

**Comment by joyyang1215** [comment]
THX
